<a href="https://colab.research.google.com/github/Lahari033/Machine-learning/blob/main/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:

df=pd.read_csv('/content/Salary_dataset.csv')
df


Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22          22              8.0  101303.0
23          23              8.3  113813.0
24          24              8.8  109432.0
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [3]:
df.head()

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [4]:
df.tail()

Unnamed: 0  YearsExperience    Salary
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [8]:
X=df.YearsExperience
y=df.Salary

In [10]:
X=df['YearsExperience'].values
Y=df['Salary'].values

In [11]:
X

array([ 1.2,  1.4,  1.6,  2.1,  2.3,  3. ,  3.1,  3.3,  3.3,  3.8,  4. ,
        4.1,  4.1,  4.2,  4.6,  5. ,  5.2,  5.4,  6. ,  6.1,  6.9,  7.2,
        8. ,  8.3,  8.8,  9.1,  9.6,  9.7, 10.4, 10.6])

In [12]:
Y

array([ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
        54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
        61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
        98274., 101303., 113813., 109432., 105583., 116970., 112636.,
       122392., 121873.])

one Method To Converting Into Array


In [13]:
X=df.iloc[:, 1].values

In [14]:
X

array([ 1.2,  1.4,  1.6,  2.1,  2.3,  3. ,  3.1,  3.3,  3.3,  3.8,  4. ,
        4.1,  4.1,  4.2,  4.6,  5. ,  5.2,  5.4,  6. ,  6.1,  6.9,  7.2,
        8. ,  8.3,  8.8,  9.1,  9.6,  9.7, 10.4, 10.6])

In [15]:
Y=df.iloc[:,-1].values

In [16]:
Y

array([ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
        54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
        61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
        98274., 101303., 113813., 109432., 105583., 116970., 112636.,
       122392., 121873.])

In [17]:
import numpy as np

In [21]:
X=np.array(X)
Y=np.array(y)

In [23]:
X=X.reshape(-1,1)
X

array([[ 1.2],
       [ 1.4],
       [ 1.6],
       [ 2.1],
       [ 2.3],
       [ 3. ],
       [ 3.1],
       [ 3.3],
       [ 3.3],
       [ 3.8],
       [ 4. ],
       [ 4.1],
       [ 4.1],
       [ 4.2],
       [ 4.6],
       [ 5. ],
       [ 5.2],
       [ 5.4],
       [ 6. ],
       [ 6.1],
       [ 6.9],
       [ 7.2],
       [ 8. ],
       [ 8.3],
       [ 8.8],
       [ 9.1],
       [ 9.6],
       [ 9.7],
       [10.4],
       [10.6]])

In [24]:
Y=Y.reshape(-1,1)
Y

array([[ 39344.],
       [ 46206.],
       [ 37732.],
       [ 43526.],
       [ 39892.],
       [ 56643.],
       [ 60151.],
       [ 54446.],
       [ 64446.],
       [ 57190.],
       [ 63219.],
       [ 55795.],
       [ 56958.],
       [ 57082.],
       [ 61112.],
       [ 67939.],
       [ 66030.],
       [ 83089.],
       [ 81364.],
       [ 93941.],
       [ 91739.],
       [ 98274.],
       [101303.],
       [113813.],
       [109432.],
       [105583.],
       [116970.],
       [112636.],
       [122392.],
       [121873.]])

In [30]:
X_mean=np.mean(X)
X_std=X.std()
X_standardized=(X-X_mean)/X_std
X_standardized

array([[-1.51005294],
       [-1.43837321],
       [-1.36669348],
       [-1.18749416],
       [-1.11581443],
       [-0.86493538],
       [-0.82909552],
       [-0.75741579],
       [-0.75741579],
       [-0.57821647],
       [-0.50653674],
       [-0.47069688],
       [-0.47069688],
       [-0.43485702],
       [-0.29149756],
       [-0.1481381 ],
       [-0.07645838],
       [-0.00477865],
       [ 0.21026054],
       [ 0.2461004 ],
       [ 0.53281931],
       [ 0.6403389 ],
       [ 0.92705781],
       [ 1.03457741],
       [ 1.21377673],
       [ 1.32129632],
       [ 1.50049564],
       [ 1.5363355 ],
       [ 1.78721455],
       [ 1.85889428]])

In [31]:
X_min=np.min(X)
X_max=np.max(X)
X_normalized=(X-X_min)/(X_max-X_min)
X_normalized

array([[0.        ],
       [0.0212766 ],
       [0.04255319],
       [0.09574468],
       [0.11702128],
       [0.19148936],
       [0.20212766],
       [0.22340426],
       [0.22340426],
       [0.27659574],
       [0.29787234],
       [0.30851064],
       [0.30851064],
       [0.31914894],
       [0.36170213],
       [0.40425532],
       [0.42553191],
       [0.44680851],
       [0.5106383 ],
       [0.5212766 ],
       [0.60638298],
       [0.63829787],
       [0.72340426],
       [0.75531915],
       [0.80851064],
       [0.84042553],
       [0.89361702],
       [0.90425532],
       [0.9787234 ],
       [1.        ]])

In [35]:
m=np.random.randn()
c=np.random.randn()
print("Randomly Initialized Slope:",m)
print("Randomly Initialized Intercept:",c)

randomly Initialized Slope: -0.059981173013498916
randomly Initialized Intercept: 1.569782986118858


In [36]:
def predict(X,m,c):
  y_predict=m*X+c
  return y_predict

In [39]:
y_pred=predict(X,m,c)

In [42]:
print("First 5 predicted Values:")
print(y_pred[:5])

First 5 predicted Values:
[[1.49780558]
 [1.48580934]
 [1.47381311]
 [1.44382252]
 [1.43182629]]


In [44]:
def compute_cost(y,y_pred):
  m=len(y)
  cost=(1/(2*m))*np.sum((y_pred-y)**2)
  return cost

In [54]:
cost=compute_cost(Y,y_pred)
print("Initial Cost(MSE):",cost)

Initial Cost(MSE): 3251553638.866667


In [53]:
m=0.0
c=0.0

y_pred=predict(X,m,c)

cost=compute_cost(Y,y_pred)
print("Cost for m=",m,"and c=",c,"is:",cost)

Cost for m= 0.0 and c= 0.0 is: 3251553638.866667


In [55]:
learning_rate=0.01
epochs=1000
print("Learning Rate:",learning_rate)
print("Epochs:",epochs)

Learning Rate: 0.01
Epochs: 1000


In [56]:
n=len(y)

In [59]:
cost_history = [] # Initialize cost_history
for epoch in range(epochs):

  y_pred=predict(X,m,c)

  dm=(1/n)*np.sum(y_pred-Y)*X # Corrected division and used Y
  dc=(1/n)*np.sum(y_pred-Y) # Corrected division and used Y

  m=m-learning_rate*dm
  c=c-learning_rate*dc

  cost=compute_cost(Y,y_pred)
  cost_history.append(cost)
  if epoch%100==0:
    print(f"Epoch: {epoch}: Cost:{cost}")

Epoch: 0: Cost:3251553638.866667
Epoch: 100: Cost:894056999.1385099
Epoch: 200: Cost:894056999.1385099
Epoch: 300: Cost:894056999.1385099
Epoch: 400: Cost:894056999.1385099
Epoch: 500: Cost:894056999.1385099
Epoch: 600: Cost:894056999.1385099
Epoch: 700: Cost:894056999.1385099
Epoch: 800: Cost:894056999.1385099
Epoch: 900: Cost:894056999.1385099


In [84]:
def predict_salary(years_experience,m,c,X_min,X_max):
  X=np.array(years_experience).reshape(-1,1)
  X_norm=(X-X_min)/(X_max-X_min)
  salary_pred=m*X_norm+c
  return salary_pred


In [85]:
print(predict_salary(5,m,c,X_min,X_max))

[[ 2963.4024976 ]
 [ 3124.73386566]
 [ 3286.06523373]
 [ 3689.39365389]
 [ 3850.72502195]
 [ 4415.38481018]
 [ 4496.05049421]
 [ 4657.38186227]
 [ 4657.38186227]
 [ 5060.71028243]
 [ 5222.0416505 ]
 [ 5302.70733453]
 [ 5302.70733453]
 [ 5383.37301856]
 [ 5706.03575469]
 [ 6028.69849082]
 [ 6190.02985888]
 [ 6351.36122695]
 [ 6835.35533114]
 [ 6916.02101517]
 [ 7561.34648743]
 [ 7803.34353953]
 [ 8448.66901178]
 [ 8690.66606388]
 [ 9093.99448404]
 [ 9335.99153613]
 [ 9739.3199563 ]
 [ 9819.98564033]
 [10384.64542855]
 [10545.97679662]]


In [78]:
years=5
predicted_salary=predict_salary(years,m,c,X_min,X_max )
print(f"Predicted salary for {years} years of experience:")
print(predicted_salary[0][0])

Predicted salary for 5 years of experience:
2963.4024975998946
